services:
  chat2api:
    image: wsng911/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
